# jobs/create-airflow-admin.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: create-airflow-admin
spec:
  template:
    spec:
      containers:
      - name: create-admin
        image: vtvito/etl_microservices:airflow
        command: ["airflow", "users", "create"]
        args: ["--username", "admin", "--firstname", "Admin", "--lastname", "User", "--role", "Admin", "--email", "admin@example.com", "--password", "admin"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
        volumeMounts:
        - mountPath: /opt/airflow
          name: airflow-data
      restartPolicy: Never
      volumes:
      - name: airflow-data
        persistentVolumeClaim:
          claimName: airflow-pv-claim
  backoffLimit: 3