# version: '3'can be ignored
services:
  airflow:
    image: apache/airflow:2.5.0
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - etl_network
    command: > 
      bash -c "airflow db init && airflow webserver"
    restart: always

  extraction_service:
    image: extraction_service  # Usa l'immagine già costruita
    volumes:
      - "C:/Users/vitod/Desktop:/app/data"  # Monta il volume necessario per l'extraction service
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - etl_network
    restart: always

  transformation_service:
    image: transformation_service  # Usa l'immagine già costruita
    expose:
      - "5002"
    ports:
      - "5002:5002"
    networks:
      - etl_network
    restart: always

networks:
  etl_network:
    driver: bridge
