services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile  # The Dockerfile for Airflow
    container_name: airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - etl-network
    restart: always

  extraction-service:
    build:
      context: ./extraction-service
      dockerfile: Dockerfile
    container_name: extraction-service
    volumes:
      - "C:/Users/vitod/Desktop:/app/data"
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - etl-network
    restart: always

  transformation-service:
    build:
      context: ./transformation-service
      dockerfile: Dockerfile
    container_name: transformation-service
    expose:
      - "5002"
    ports:
      - "5002:5002"
    networks:
      - etl-network
    restart: always

networks:   # create a network to allows comunication between services
  etl-network:
    driver: bridge