services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile  # The Dockerfile for Airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - etl_network
    restart: always

  extraction_service:
    build:
      context: ./extraction_service
      dockerfile: Dockerfile
    volumes:
      - "C:/Users/vitod/Desktop:/app/data"
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - etl_network
    restart: always

  transformation_service:
    build:
      context: ./transformation_service
      dockerfile: Dockerfile
    expose:
      - "5002"
    ports:
      - "5002:5002"
    networks:
      - etl_network
    restart: always

networks:   # create a network to allows comunication between services
  etl_network:
    driver: bridge