services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - etl-data:/app/data  # Shared volume
    ports:
      - "8080:8080"
    networks:
      - etl-network
    restart: always

  extraction-service:
    build:
      context: ./extraction-service
      dockerfile: Dockerfile
    container_name: extraction-service
    volumes:
      - etl-data:/app/data  # Mount shared volume
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - etl-network
    restart: always

  transformation-service:
    build:
      context: ./transformation-service
      dockerfile: Dockerfile
    container_name: transformation-service
    volumes:
      - etl-data:/app/data  # Mount shared volume
    expose:
      - "5002"
    ports:
      - "5002:5002"
    networks:
      - etl-network
    restart: always

  load-service:
    build:
      context: ./load-service
      dockerfile: Dockerfile
    container_name: load-service
    volumes:
      - etl-data:/app/data  # Mount shared volume
    expose:
      - "5003"
    ports:
      - "5003:5003"
    networks:
      - etl-network
    restart: always

networks:
  etl-network:
    driver: bridge

volumes:
  etl-data: