# Questo file definisce i job e i target che Prometheus deve monitorare

global:
  scrape_interval: 15s  # Intervallo di raccolta delle metriche

scrape_configs:

  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'read-csv-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['read-csv-service:5001']

  - job_name: 'clean-nan-csv-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['clean-nan-csv-service:5002']

  - job_name: 'get-columns-csv-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['get-columns-csv-service:5003']

  - job_name: 'delete-columns-csv-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['delete-columns-csv-service:5004']