apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: etl-microservices
spec:
  selector:
    app: airflow
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer  # Expose the Airflow outside the cluster
