apiVersion: v1
kind: Service
metadata:
  name: extraction-service
  namespace: etl-microservices
spec:
  selector:
    app: extraction-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP