apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out ./kubernetes
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: airflow
