apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: etl-data-airflow
  name: etl-data-airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi