apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: etl-prometheus-data
  name: etl-prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi