apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out ./kubernetes
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: delete-columns-csv-service
  name: delete-columns-csv-service
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 5004
  selector:
    io.kompose.service: delete-columns-csv-service
