apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out ./kubernetes
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: get-columns-csv-service
  name: get-columns-csv-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: get-columns-csv-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out ./kubernetes
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: get-columns-csv-service
    spec:
      containers:
        - image: vtvito/etl_microservices:get-columns-csv-service
          name: get-columns-csv-service
          ports:
            - containerPort: 5003
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: etl-containers-shared-data
      restartPolicy: Always
      volumes:
        - name: etl-containers-shared-data
          persistentVolumeClaim:
            claimName: etl-containers-shared-data
